#ifndef MAINAPP_STATUS_H
#define MAINAPP_STATUS_H

enum class Status
{
    ASMCHOOSED,
    CPPCHOOSED,
    START,
    CHANGETO1IMAGE,
    CHANGETO2IMAGE,
    CHANGETO3IMAGE,
    THREAD1,
    THREAD2,
    THREAD4,
    THREAD8,
    THREAD16,
    THREAD32,
    THREAD64,
    EROSION,
    DILATATION
};

#endif MAINAPP_STATUS_H
